# Generated by Django 3.1.7 on 2021-06-20 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for identifying token', max_length=255)),
                ('token', models.CharField(blank=True, default='', max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'URL Token',
                'verbose_name_plural': 'URL Tokens',
            },
        ),
    ]
